In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
census = pd.read_csv('../data/census_davidson.csv')
census.head()

,Label (Grouping),United States!!Number!!Estimate,United States!!Number!!Margin of Error,United States!!Percent Distribution!!Estimate,United States!!Percent Distribution!!Margin of Error,United States!!Median income (dollars)!!Estimate,United States!!Median income (dollars)!!Margin of Error,ZCTA5 37013!!Number!!Estimate,ZCTA5 37013!!Number!!Margin of Error,ZCTA5 37013!!Percent Distribution!!Estimate,...,ZCTA5 37243!!Percent Distribution!!Estimate,ZCTA5 37243!!Percent Distribution!!Margin of Error,ZCTA5 37243!!Median income (dollars)!!Estimate,ZCTA5 37243!!Median income (dollars)!!Margin of Error,ZCTA5 37246!!Number!!Estimate,ZCTA5 37246!!Number!!Margin of Error,ZCTA5 37246!!Percent Distribution!!Estimate,ZCTA5 37246!!Percent Distribution!!Margin of Error,ZCTA5 37246!!Median income (dollars)!!Estimate,ZCTA5 37246!!Median income (dollars)!!Margin of Error
0,HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Households,"122,354,219","±211,970","122,354,219","±211,970","64,994",±128,"36,217","±1,265","36,217",...,0,±13,-,**,0.0,±13,0,±13,-,**
2,One race--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,White,"91,401,117","±188,550",74.7%,±0.1,"68,943",±143,"18,715","±1,081",51.7%,...,-,**,-,**,0.0,±13,-,**,-,**
4,Black or African American,"15,022,079","±25,717",12.3%,±0.1,"43,674",±139,"14,048",±944,38.8%,...,-,**,-,**,0.0,±13,-,**,-,**

In [3]:
census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Columns: 217 entries, Label (Grouping) to ZCTA5 37246!!Median income (dollars)!!Margin of Error
dtypes: float64(6), object(211)
memory usage: 79.8+ KB

In [4]:
census

,Label (Grouping),United States!!Number!!Estimate,United States!!Number!!Margin of Error,United States!!Percent Distribution!!Estimate,United States!!Percent Distribution!!Margin of Error,United States!!Median income (dollars)!!Estimate,United States!!Median income (dollars)!!Margin of Error,ZCTA5 37013!!Number!!Estimate,ZCTA5 37013!!Number!!Margin of Error,ZCTA5 37013!!Percent Distribution!!Estimate,...,ZCTA5 37243!!Percent Distribution!!Estimate,ZCTA5 37243!!Percent Distribution!!Margin of Error,ZCTA5 37243!!Median income (dollars)!!Estimate,ZCTA5 37243!!Median income (dollars)!!Margin of Error,ZCTA5 37246!!Number!!Estimate,ZCTA5 37246!!Number!!Margin of Error,ZCTA5 37246!!Percent Distribution!!Estimate,ZCTA5 37246!!Percent Distribution!!Margin of Error,ZCTA5 37246!!Median income (dollars)!!Estimate,ZCTA5 37246!!Median income (dollars)!!Margin of Error
0,HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Households,"122,354,219","±211,970","122,354,219","±211,970","64,994",±128,"36,217","±1,265","36,217",...,0,±13,-,**,0.0,±13,0,±13,-,**
2,One race--,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,White,"91,401,117","±188,550",74.7%,±0.1,"68,943",±143,"18,715","±1,081",51.7%,...,-,**,-,**,0.0,±13,-,**,-,**
4,Black or African American,"15,022,079","±25,717",12.3%,±0.1,"43,674",±139,"14,048",±944,38.8%,...,-,**,-,**,0.0,±13,-,**,-,**
5,American Indian and Alaska Native,"874,615","±5,438",0.7%,±0.1,"45,877",±436,18,±24,0.0%,...,-,**,-,**,0.0,±13,-,**,-,**
6,Asian,"5,951,521","±18,786",4.9%,±0.1,"91,775",±366,"1,188",±266,3.3%,...,-,**,-,**,0.0,±13,-,**,-,**
7,Native Hawaiian and Other Pacific ...,"165,707","±2,449",0.1%,±0.1,"65,804","±1,325",0,±31,0.0%,...,-,**,-,**,0.0,±13,-,**,-,**
8,Some other race,"4,572,575","±22,873",3.7%,±0.1,"51,900",±231,981,±355,2.7%,...,-,**,-,**,0.0,±13,-,**,-,**
9,Two or more races,"4,366,605","±18,905",3.6%,±0.1,"61,870",±332,"1,267",±381,3.5%,...,-,**,-,**,0.0,±13,-,**,-,**
10,Hispanic or Latino origin (of any race),"16,412,997","±35,790",13.4%,±0.1,"54,632",±190,"4,085",±515,11.3%,...,-,**,-,**,0.0,±13,-,**,-,**
11,"White alone, not Hispanic or Latino","81,866,282","±149,335",66.9%,±0.1,"70,843",±122,"15,953","±1,074",44.0%,...,-,**,-,**,0.0,±13,-,**,-,**
12,HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,15 to 24 years,"4,443,060","±30,069",3.6%,±0.1,"34,805",±171,"1,949",±438,5.4%,...,-,**,-,**,0.0,±13,-,**,-,**
14,25 to 44 years,"39,575,151","±66,644",32.3%,±0.1,"71,738",±225,"17,953","±1,211",49.6%,...,-,**,-,**,0.0,±13,-,**,-,**
15,45 to 64 years,"46,246,268","±38,365",37.8%,±0.1,"78,550",±276,"12,325",±905,34.0%,...,-,**,-,**,0.0,±13,-,**,-,**
16,65 years and over,"32,089,740","±95,297",26.2%,±0.1,"47,484",±87,"3,990",±454,11.0%,...,-,**,-,**,0.0,±13,-,**,-,**
17,FAMILIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Families,"79,849,830","±199,011","79,849,830","±199,011","80,069",±207,"23,302","±1,279","23,302",...,0,±13,-,**,0.0,±13,0,±13,-,**
19,With own children of householder under...,"33,410,645","±162,024",41.8%,±0.1,"77,445",±387,"11,886","±1,097",51.0%,...,-,**,-,**,0.0,±13,-,**,-,**
20,With no own children of householder un...,"46,439,185","±53,029",58.2%,±0.1,"81,502",±143,"11,416",±773,49.0%,...,-,**,-,**,0.0,±13,-,**,-,**
21,Married-couple families,"58,807,003","±252,933",73.6%,±0.1,"95,485",±192,"15,188","±1,019",65.2%,...,-,**,-,**,0.0,±13,-,**,-,**
22,With own children under 18 years,"22,836,022","±185,305",28.6%,±0.2,"103,364",±230,"8,029",±893,34.5%,...,-,**,-,**,0.0,±13,-,**,-,**
23,"Female householder, no spouse present","15,086,810","±38,893",18.9%,±0.1,"40,325",±105,"5,933",±789,25.5%,...,-,**,-,**,0.0,±13,-,**,-,**
24,With own children under 18 years,"7,814,891","±22,783",9.8%,±0.1,"30,681",±99,"3,026",±485,13.0%,...,-,**,-,**,0.0,±13,-,**,-,**
25,"Male householder, no spouse present","5,956,017","±31,283",7.5%,±0.1,"55,166",±197,"2,181",±425,9.4%,...,-,**,-,**,0.0,±13,-,**,-,**
26,With own children under 18 years,"2,759,732","±16,038",3.5%,±0.1,"47,375",±245,831,±250,3.6%,...,-,**,-,**,0.0,±13,-,**,-,**
27,FAMILY INCOME BY FAMILY SIZE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2-person families,"37,163,444","±69,552",46.5%,±0.1,"70,545",±143,"9,477",±876,40.7%,...,-,**,-,**,0.0,±13,-,**,-,**
29,3-person families,"17,635,604","±103,681",22.1%,±0.1,"82,024",±325,"4,476",±571,19.2%,...,-,**,-,**,0.0,±13,-,**,-,**
30,4-person families,"14,572,032","±98,843",18.2%,±0.1,"98,487",±338,"5,221",±902,22.4%,...,-,**,-,**,0.0,±13,-,**,-,**
31,5-person families,"6,575,601","±24,635",8.2%,±0.1,"91,080",±371,"2,427",±484,10.4%,...,-,**,-,**,0.0,±13,-,**,-,**
32,6-person families,"2,453,069","±27,856",3.1%,±0.1,"87,703",±489,"1,021",±205,4.4%,...,-,**,-,**,0.0,±13,-,**,-,**
33,7-or-more person families,"1,450,080","±20,985",1.8%,±0.1,"91,346",±639,680,±217,2.9%,...,-,**,-,**,0.0,±13,-,**,-,**
34,FAMILY INCOME BY NUMBER OF EARNERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,No earners,"11,659,044","±25,347",14.6%,±0.1,"42,127",±173,"1,355",±283,5.8%,...,-,**,-,**,0.0,±13,-,**,-,**
36,1 earner,"25,471,444","±35,226",31.9%,±0.1,"55,161",±173,"7,643",±915,32.8%,...,-,**,-,**,0.0,±13,-,**,-,**
37,2 earners,"33,288,028","±169,454",41.7%,±0.1,"102,000",±168,"11,201","±1,016",48.1%,...,-,**,-,**,0.0,±13,-,**,-,**
38,3 or more earners,"9,431,314","±36,959",11.8%,±0.1,"125,061",±231,"3,103",±576,13.3%,...,-,**,-,**,0.0,±13,-,**,-,**
39,NONFAMILY HOUSEHOLDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Nonfamily households,"42,504,389","±49,626","42,504,389","±49,626","39,027",±83,"12,915",±979,"12,915",...,0,±13,-,**,0.0,±13,0,±13,-,**
41,Female householder,"22,650,095","±51,470",53.3%,±0.1,"33,917",±82,"6,193",±786,48.0%,...,-,**,-,**,0.0,±13,-,**,-,**
42,Living alone,"18,957,732","±54,441",44.6%,±0.1,"29,874",±76,"4,925",±744,38.1%,...,-,**,-,**,0.0,±13,-,**,-,**
43,Not living alone,"3,692,363","±15,164",8.7%,±0.1,"67,442",±277,"1,268",±369,9.8%,...,-,**,-,**,0.0,±13,-,**,-,**
44,Male householder,"19,854,294","±38,534",46.7%,±0.1,"45,114",±132,"6,722",±715,52.0%,...,-,**,-,**,0.0,±13,-,**,-,**
45,Living alone,"15,296,800","±29,782",36.0%,±0.1,"38,669",±118,"4,529",±575,35.1%,...,-,**,-,**,0.0,±13,-,**,-,**
46,Not living alone,"4,557,494","±27,381",10.7%,±0.1,"74,902",±276,"2,193",±498,17.0%,...,-,**,-,**,0.0,±13,-,**,-,**

In [5]:
census_df = census.transpose()
census_df

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,Some other race,Two or more races,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
United States!!Number!!Estimate,NaN,"122,354,219",NaN,"91,401,117","15,022,079","874,615","5,951,521","165,707","4,572,575","4,366,605",...,"33,288,028","9,431,314",NaN,"42,504,389","22,650,095","18,957,732","3,692,363","19,854,294","15,296,800","4,557,494"
United States!!Number!!Margin of Error,NaN,"±211,970",NaN,"±188,550","±25,717","±5,438","±18,786","±2,449","±22,873","±18,905",...,"±169,454","±36,959",NaN,"±49,626","±51,470","±54,441","±15,164","±38,534","±29,782","±27,381"
United States!!Percent Distribution!!Estimate,NaN,"122,354,219",NaN,74.7%,12.3%,0.7%,4.9%,0.1%,3.7%,3.6%,...,41.7%,11.8%,NaN,"42,504,389",53.3%,44.6%,8.7%,46.7%,36.0%,10.7%
United States!!Percent Distribution!!Margin of Error,NaN,"±211,970",NaN,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,NaN,"±49,626",±0.1,±0.1,±0.1,±0.1,±0.1,±0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZCTA5 37246!!Number!!Margin of Error,NaN,±13,NaN,±13,±13,±13,±13,±13,±13,±13,...,±13,±13,NaN,±13,±13,±13,±13,±13,±13,±13
ZCTA5 37246!!Percent Distribution!!Estimate,NaN,0,NaN,-,-,-,-,-,-,-,...,-,-,NaN,0,-,-,-,-,-,-
ZCTA5 37246!!Percent Distribution!!Margin of Error,NaN,±13,NaN,**,**,**,**,**,**,**,...,**,**,NaN,±13,**,**,**,**,**,**
ZCTA5 37246!!Median income (dollars)!!Estimate,NaN,-,NaN,-,-,-,-,-,-,-,...,-,-,NaN,-,-,-,-,-,-,-
ZCTA5 37246!!Median income (dollars)!!Margin of Error,NaN,**,NaN,**,**,**,**,**,**,**,...,**,**,NaN,**,**,**,**,**,**,**

In [6]:
census_df = census_df.reset_index()

In [7]:
census_df

,index,0,1,2,3,4,5,6,7,8,...,37,38,39,40,41,42,43,44,45,46
0,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,Some other race,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
1,United States!!Number!!Estimate,NaN,"122,354,219",NaN,"91,401,117","15,022,079","874,615","5,951,521","165,707","4,572,575",...,"33,288,028","9,431,314",NaN,"42,504,389","22,650,095","18,957,732","3,692,363","19,854,294","15,296,800","4,557,494"
2,United States!!Number!!Margin of Error,NaN,"±211,970",NaN,"±188,550","±25,717","±5,438","±18,786","±2,449","±22,873",...,"±169,454","±36,959",NaN,"±49,626","±51,470","±54,441","±15,164","±38,534","±29,782","±27,381"
3,United States!!Percent Distribution!!Estimate,NaN,"122,354,219",NaN,74.7%,12.3%,0.7%,4.9%,0.1%,3.7%,...,41.7%,11.8%,NaN,"42,504,389",53.3%,44.6%,8.7%,46.7%,36.0%,10.7%
4,United States!!Percent Distribution!!Margin of...,NaN,"±211,970",NaN,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,NaN,"±49,626",±0.1,±0.1,±0.1,±0.1,±0.1,±0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,ZCTA5 37246!!Number!!Margin of Error,NaN,±13,NaN,±13,±13,±13,±13,±13,±13,...,±13,±13,NaN,±13,±13,±13,±13,±13,±13,±13
213,ZCTA5 37246!!Percent Distribution!!Estimate,NaN,0,NaN,-,-,-,-,-,-,...,-,-,NaN,0,-,-,-,-,-,-
214,ZCTA5 37246!!Percent Distribution!!Margin of E...,NaN,±13,NaN,**,**,**,**,**,**,...,**,**,NaN,±13,**,**,**,**,**,**
215,ZCTA5 37246!!Median income (dollars)!!Estimate,NaN,-,NaN,-,-,-,-,-,-,...,-,-,NaN,-,-,-,-,-,-,-
216,ZCTA5 37246!!Median income (dollars)!!Margin o...,NaN,**,NaN,**,**,**,**,**,**,...,**,**,NaN,**,**,**,**,**,**,**

In [8]:
zip_codes = []

for x in census_df['index']:
    v = re.findall(r'Label', x)
    y = re.findall(r'United States', x)
    z = re.findall(r'\d{5}', x)
    if v:
        zip_codes.append(v)
    if y:
        zip_codes.append(y)
    if z:
        zip_codes.append(z)

zip_codes

[['Label'],
 ['United States'],
 ['United States'],
 ['United States'],
 ['United States'],
 ['United States'],
 ['United States'],
 ['37013'],
 ['37013'],
 ['37013'],
 ['37013'],
 ['37013'],
 ['37013'],
 ['37027'],
 ['37027'],
 ['37027'],
 ['37027'],
 ['37027'],
 ['37027'],
 ['37072'],
 ['37072'],
 ['37072'],
 ['37072'],
 ['37072'],
 ['37072'],
 ['37076'],
 ['37076'],
 ['37076'],
 ['37076'],
 ['37076'],
 ['37076'],
 ['37080'],
 ['37080'],
 ['37080'],
 ['37080'],
 ['37080'],
 ['37080'],
 ['37086'],
 ['37086'],
 ['37086'],
 ['37086'],
 ['37086'],
 ['37086'],
 ['37115'],
 ['37115'],
 ['37115'],
 ['37115'],
 ['37115'],
 ['37115'],
 ['37135'],
 ['37135'],
 ['37135'],
 ['37135'],
 ['37135'],
 ['37135'],
 ['37138'],
 ['37138'],
 ['37138'],
 ['37138'],
 ['37138'],
 ['37138'],
 ['37143'],
 ['37143'],
 ['37143'],
 ['37143'],
 ['37143'],
 ['37143'],
 ['37189'],
 ['37189'],
 ['37189'],
 ['37189'],
 ['37189'],
 ['37189'],
 ['37201'],
 ['37201'],
 ['37201'],
 ['37201'],
 ['37201'],
 ['37201'],
 ['37203'],
 ['37203'],
 ['37203'],
 ['37203'],
 ['37203'],
 ['37203'],
 ['37204'],
 ['37204'],
 ['37204'],
 ['37204'],
 ['37204'],
 ['37204'],
 ['37205'],
 ['37205'],
 ['37205'],
 ['37205'],
 ['37205'],
 ['37205'],
 ['37206'],
 ['37206'],
 ['37206'],
 ['37206'],
 ['37206'],
 ['37206'],
 ['37207'],
 ['37207'],
 ['37207'],
 ['37207'],
 ['37207'],
 ['37207'],
 ['37208'],
 ['37208'],
 ['37208'],
 ['37208'],
 ['37208'],
 ['37208'],
 ['37209'],
 ['37209'],
 ['37209'],
 ['37209'],
 ['37209'],
 ['37209'],
 ['37210'],
 ['37210'],
 ['37210'],
 ['37210'],
 ['37210'],
 ['37210'],
 ['37211'],
 ['37211'],
 ['37211'],
 ['37211'],
 ['37211'],
 ['37211'],
 ['37212'],
 ['37212'],
 ['37212'],
 ['37212'],
 ['37212'],
 ['37212'],
 ['37213'],
 ['37213'],
 ['37213'],
 ['37213'],
 ['37213'],
 ['37213'],
 ['37214'],
 ['37214'],
 ['37214'],
 ['37214'],
 ['37214'],
 ['37214'],
 ['37215'],
 ['37215'],
 ['37215'],
 ['37215'],
 ['37215'],
 ['37215'],
 ['37216'],
 ['37216'],
 ['37216'],
 ['37216'],
 ['37216'],
 ['37216'],
 ['37217'],
 ['37217'],
 ['37217'],
 ['37217'],
 ['37217'],
 ['37217'],
 ['37218'],
 ['37218'],
 ['37218'],
 ['37218'],
 ['37218'],
 ['37218'],
 ['37219'],
 ['37219'],
 ['37219'],
 ['37219'],
 ['37219'],
 ['37219'],
 ['37220'],
 ['37220'],
 ['37220'],
 ['37220'],
 ['37220'],
 ['37220'],
 ['37221'],
 ['37221'],
 ['37221'],
 ['37221'],
 ['37221'],
 ['37221'],
 ['37228'],
 ['37228'],
 ['37228'],
 ['37228'],
 ['37228'],
 ['37228'],
 ['37240'],
 ['37240'],
 ['37240'],
 ['37240'],
 ['37240'],
 ['37240'],
 ['37243'],
 ['37243'],
 ['37243'],
 ['37243'],
 ['37243'],
 ['37243'],
 ['37246'],
 ['37246'],
 ['37246'],
 ['37246'],
 ['37246'],
 ['37246']]

In [9]:
zip_codes = pd.DataFrame(zip_codes, columns = ['zip_codes'])
zip_codes

         zip_codes
0            Label
1    United States
2    United States
3    United States
4    United States
..             ...
212          37246
213          37246
214          37246
215          37246
216          37246

[217 rows x 1 columns]

In [10]:
census_df = pd.merge(census_df, zip_codes, left_index = True, right_index = True)
census_df

,index,0,1,2,3,4,5,6,7,8,...,38,39,40,41,42,43,44,45,46,zip_codes
0,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,Some other race,...,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone,Label
1,United States!!Number!!Estimate,NaN,"122,354,219",NaN,"91,401,117","15,022,079","874,615","5,951,521","165,707","4,572,575",...,"9,431,314",NaN,"42,504,389","22,650,095","18,957,732","3,692,363","19,854,294","15,296,800","4,557,494",United States
2,United States!!Number!!Margin of Error,NaN,"±211,970",NaN,"±188,550","±25,717","±5,438","±18,786","±2,449","±22,873",...,"±36,959",NaN,"±49,626","±51,470","±54,441","±15,164","±38,534","±29,782","±27,381",United States
3,United States!!Percent Distribution!!Estimate,NaN,"122,354,219",NaN,74.7%,12.3%,0.7%,4.9%,0.1%,3.7%,...,11.8%,NaN,"42,504,389",53.3%,44.6%,8.7%,46.7%,36.0%,10.7%,United States
4,United States!!Percent Distribution!!Margin of...,NaN,"±211,970",NaN,±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,NaN,"±49,626",±0.1,±0.1,±0.1,±0.1,±0.1,±0.1,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,ZCTA5 37246!!Number!!Margin of Error,NaN,±13,NaN,±13,±13,±13,±13,±13,±13,...,±13,NaN,±13,±13,±13,±13,±13,±13,±13,37246
213,ZCTA5 37246!!Percent Distribution!!Estimate,NaN,0,NaN,-,-,-,-,-,-,...,-,NaN,0,-,-,-,-,-,-,37246
214,ZCTA5 37246!!Percent Distribution!!Margin of E...,NaN,±13,NaN,**,**,**,**,**,**,...,**,NaN,±13,**,**,**,**,**,**,37246
215,ZCTA5 37246!!Median income (dollars)!!Estimate,NaN,-,NaN,-,-,-,-,-,-,...,-,NaN,-,-,-,-,-,-,-,37246
216,ZCTA5 37246!!Median income (dollars)!!Margin o...,NaN,**,NaN,**,**,**,**,**,**,...,**,NaN,**,**,**,**,**,**,**,37246

In [11]:
census_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 49 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      217 non-null    object
 1   0          1 non-null      object
 2   1          217 non-null    object
 3   2          1 non-null      object
 4   3          217 non-null    object
 5   4          217 non-null    object
 6   5          217 non-null    object
 7   6          217 non-null    object
 8   7          217 non-null    object
 9   8          217 non-null    object
 10  9          217 non-null    object
 11  10         217 non-null    object
 12  11         217 non-null    object
 13  12         1 non-null      object
 14  13         217 non-null    object
 15  14         217 non-null    object
 16  15         217 non-null    object
 17  16         217 non-null    object
 18  17         1 non-null      object
 19  18         217 non-null    object
 20  19         217 non-null    object
 21  20         217 non-null    object
 22  21         217 non-null    object
 23  22         217 non-null    object
 24  23         217 non-null    object
 25  24         217 non-null    object
 26  25         217 non-null    object
 27  26         217 non-null    object
 28  27         1 non-null      object
 29  28         217 non-null    object
 30  29         217 non-null    object
 31  30         217 non-null    object
 32  31         217 non-null    object
 33  32         217 non-null    object
 34  33         217 non-null    object
 35  34         1 non-null      object
 36  35         217 non-null    object
 37  36         217 non-null    object
 38  37         217 non-null    object
 39  38         217 non-null    object
 40  39         1 non-null      object
 41  40         217 non-null    object
 42  41         217 non-null    object
 43  42         217 non-null    object
 44  43         217 non-null    object
 45  44         217 non-null    object
 46  45         217 non-null    object
 47  46         217 non-null    object
 48  zip_codes  217 non-null    object
dtypes: object(49)
memory usage: 83.2+ KB

In [12]:
census_clean = census_df.iloc[:, [48, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]]
census_clean

,zip_codes,index,0,1,2,3,4,5,6,7,...,37,38,39,40,41,42,43,44,45,46
0,Label,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
1,United States,United States!!Number!!Estimate,NaN,"122,354,219",NaN,"91,401,117","15,022,079","874,615","5,951,521","165,707",...,"33,288,028","9,431,314",NaN,"42,504,389","22,650,095","18,957,732","3,692,363","19,854,294","15,296,800","4,557,494"
2,United States,United States!!Number!!Margin of Error,NaN,"±211,970",NaN,"±188,550","±25,717","±5,438","±18,786","±2,449",...,"±169,454","±36,959",NaN,"±49,626","±51,470","±54,441","±15,164","±38,534","±29,782","±27,381"
3,United States,United States!!Percent Distribution!!Estimate,NaN,"122,354,219",NaN,74.7%,12.3%,0.7%,4.9%,0.1%,...,41.7%,11.8%,NaN,"42,504,389",53.3%,44.6%,8.7%,46.7%,36.0%,10.7%
4,United States,United States!!Percent Distribution!!Margin of...,NaN,"±211,970",NaN,±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,NaN,"±49,626",±0.1,±0.1,±0.1,±0.1,±0.1,±0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,37246,ZCTA5 37246!!Number!!Margin of Error,NaN,±13,NaN,±13,±13,±13,±13,±13,...,±13,±13,NaN,±13,±13,±13,±13,±13,±13,±13
213,37246,ZCTA5 37246!!Percent Distribution!!Estimate,NaN,0,NaN,-,-,-,-,-,...,-,-,NaN,0,-,-,-,-,-,-
214,37246,ZCTA5 37246!!Percent Distribution!!Margin of E...,NaN,±13,NaN,**,**,**,**,**,...,**,**,NaN,±13,**,**,**,**,**,**
215,37246,ZCTA5 37246!!Median income (dollars)!!Estimate,NaN,-,NaN,-,-,-,-,-,...,-,-,NaN,-,-,-,-,-,-,-
216,37246,ZCTA5 37246!!Median income (dollars)!!Margin o...,NaN,**,NaN,**,**,**,**,**,...,**,**,NaN,**,**,**,**,**,**,**

In [13]:
census_clean.columns = census_clean.iloc[0]
census_clean

,Label,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific Islander,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
0,Label,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
1,United States,United States!!Number!!Estimate,NaN,"122,354,219",NaN,"91,401,117","15,022,079","874,615","5,951,521","165,707",...,"33,288,028","9,431,314",NaN,"42,504,389","22,650,095","18,957,732","3,692,363","19,854,294","15,296,800","4,557,494"
2,United States,United States!!Number!!Margin of Error,NaN,"±211,970",NaN,"±188,550","±25,717","±5,438","±18,786","±2,449",...,"±169,454","±36,959",NaN,"±49,626","±51,470","±54,441","±15,164","±38,534","±29,782","±27,381"
3,United States,United States!!Percent Distribution!!Estimate,NaN,"122,354,219",NaN,74.7%,12.3%,0.7%,4.9%,0.1%,...,41.7%,11.8%,NaN,"42,504,389",53.3%,44.6%,8.7%,46.7%,36.0%,10.7%
4,United States,United States!!Percent Distribution!!Margin of...,NaN,"±211,970",NaN,±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,NaN,"±49,626",±0.1,±0.1,±0.1,±0.1,±0.1,±0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,37246,ZCTA5 37246!!Number!!Margin of Error,NaN,±13,NaN,±13,±13,±13,±13,±13,...,±13,±13,NaN,±13,±13,±13,±13,±13,±13,±13
213,37246,ZCTA5 37246!!Percent Distribution!!Estimate,NaN,0,NaN,-,-,-,-,-,...,-,-,NaN,0,-,-,-,-,-,-
214,37246,ZCTA5 37246!!Percent Distribution!!Margin of E...,NaN,±13,NaN,**,**,**,**,**,...,**,**,NaN,±13,**,**,**,**,**,**
215,37246,ZCTA5 37246!!Median income (dollars)!!Estimate,NaN,-,NaN,-,-,-,-,-,...,-,-,NaN,-,-,-,-,-,-,-
216,37246,ZCTA5 37246!!Median income (dollars)!!Margin o...,NaN,**,NaN,**,**,**,**,**,...,**,**,NaN,**,**,**,**,**,**,**

In [14]:
census_clean = census_clean.rename(columns = {'Label': 'Zip Codes'})
census_clean

,Zip Codes,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific Islander,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
0,Label,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
1,United States,United States!!Number!!Estimate,NaN,"122,354,219",NaN,"91,401,117","15,022,079","874,615","5,951,521","165,707",...,"33,288,028","9,431,314",NaN,"42,504,389","22,650,095","18,957,732","3,692,363","19,854,294","15,296,800","4,557,494"
2,United States,United States!!Number!!Margin of Error,NaN,"±211,970",NaN,"±188,550","±25,717","±5,438","±18,786","±2,449",...,"±169,454","±36,959",NaN,"±49,626","±51,470","±54,441","±15,164","±38,534","±29,782","±27,381"
3,United States,United States!!Percent Distribution!!Estimate,NaN,"122,354,219",NaN,74.7%,12.3%,0.7%,4.9%,0.1%,...,41.7%,11.8%,NaN,"42,504,389",53.3%,44.6%,8.7%,46.7%,36.0%,10.7%
4,United States,United States!!Percent Distribution!!Margin of...,NaN,"±211,970",NaN,±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,NaN,"±49,626",±0.1,±0.1,±0.1,±0.1,±0.1,±0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,37246,ZCTA5 37246!!Number!!Margin of Error,NaN,±13,NaN,±13,±13,±13,±13,±13,...,±13,±13,NaN,±13,±13,±13,±13,±13,±13,±13
213,37246,ZCTA5 37246!!Percent Distribution!!Estimate,NaN,0,NaN,-,-,-,-,-,...,-,-,NaN,0,-,-,-,-,-,-
214,37246,ZCTA5 37246!!Percent Distribution!!Margin of E...,NaN,±13,NaN,**,**,**,**,**,...,**,**,NaN,±13,**,**,**,**,**,**
215,37246,ZCTA5 37246!!Median income (dollars)!!Estimate,NaN,-,NaN,-,-,-,-,-,...,-,-,NaN,-,-,-,-,-,-,-
216,37246,ZCTA5 37246!!Median income (dollars)!!Margin o...,NaN,**,NaN,**,**,**,**,**,...,**,**,NaN,**,**,**,**,**,**,**

In [15]:
census_clean = census_clean.drop(labels = 0, axis = 0)
census_clean

,Zip Codes,Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER,Households,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific Islander,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
1,United States,United States!!Number!!Estimate,NaN,"122,354,219",NaN,"91,401,117","15,022,079","874,615","5,951,521","165,707",...,"33,288,028","9,431,314",NaN,"42,504,389","22,650,095","18,957,732","3,692,363","19,854,294","15,296,800","4,557,494"
2,United States,United States!!Number!!Margin of Error,NaN,"±211,970",NaN,"±188,550","±25,717","±5,438","±18,786","±2,449",...,"±169,454","±36,959",NaN,"±49,626","±51,470","±54,441","±15,164","±38,534","±29,782","±27,381"
3,United States,United States!!Percent Distribution!!Estimate,NaN,"122,354,219",NaN,74.7%,12.3%,0.7%,4.9%,0.1%,...,41.7%,11.8%,NaN,"42,504,389",53.3%,44.6%,8.7%,46.7%,36.0%,10.7%
4,United States,United States!!Percent Distribution!!Margin of...,NaN,"±211,970",NaN,±0.1,±0.1,±0.1,±0.1,±0.1,...,±0.1,±0.1,NaN,"±49,626",±0.1,±0.1,±0.1,±0.1,±0.1,±0.1
5,United States,United States!!Median income (dollars)!!Estimate,NaN,"64,994",NaN,"68,943","43,674","45,877","91,775","65,804",...,"102,000","125,061",NaN,"39,027","33,917","29,874","67,442","45,114","38,669","74,902"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,37246,ZCTA5 37246!!Number!!Margin of Error,NaN,±13,NaN,±13,±13,±13,±13,±13,...,±13,±13,NaN,±13,±13,±13,±13,±13,±13,±13
213,37246,ZCTA5 37246!!Percent Distribution!!Estimate,NaN,0,NaN,-,-,-,-,-,...,-,-,NaN,0,-,-,-,-,-,-
214,37246,ZCTA5 37246!!Percent Distribution!!Margin of E...,NaN,±13,NaN,**,**,**,**,**,...,**,**,NaN,±13,**,**,**,**,**,**
215,37246,ZCTA5 37246!!Median income (dollars)!!Estimate,NaN,-,NaN,-,-,-,-,-,...,-,-,NaN,-,-,-,-,-,-,-
216,37246,ZCTA5 37246!!Median income (dollars)!!Margin o...,NaN,**,NaN,**,**,**,**,**,...,**,**,NaN,**,**,**,**,**,**,**

In [16]:
census_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 1 to 216
Data columns (total 49 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   Zip Codes                                                              216 non-null    object
 1   Label (Grouping)                                                       216 non-null    object
 2   HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER  0 non-null      object
 3       Households                                                         216 non-null    object
 4           One race--                                                     0 non-null      object
 5               White                                                      216 non-null    object
 6               Black or African American                                  216 non-null    object
 7               American Indian and Alaska Native                          216 non-null    object
 8               Asian                                                      216 non-null    object
 9               Native Hawaiian and Other Pacific Islander                 216 non-null    object
 10              Some other race                                            216 non-null    object
 11          Two or more races                                              216 non-null    object
 12          Hispanic or Latino origin (of any race)                        216 non-null    object
 13          White alone, not Hispanic or Latino                            216 non-null    object
 14  HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER                                 0 non-null      object
 15      15 to 24 years                                                     216 non-null    object
 16      25 to 44 years                                                     216 non-null    object
 17      45 to 64 years                                                     216 non-null    object
 18      65 years and over                                                  216 non-null    object
 19  FAMILIES                                                               0 non-null      object
 20      Families                                                           216 non-null    object
 21          With own children of householder under 18 years                216 non-null    object
 22          With no own children of householder under 18 years             216 non-null    object
 23          Married-couple families                                        216 non-null    object
 24              With own children under 18 years                           216 non-null    object
 25          Female householder, no spouse present                          216 non-null    object
 26              With own children under 18 years                           216 non-null    object
 27          Male householder, no spouse present                            216 non-null    object
 28              With own children under 18 years                           216 non-null    object
 29  FAMILY INCOME BY FAMILY SIZE                                           0 non-null      object
 30      2-person families                                                  216 non-null    object
 31      3-person families                                                  216 non-null    object
 32      4-person families                                                  216 non-null    object
 33      5-person families                                                  216 non-null    object
 34      6-person families                                                  216 non-null    object
 35      7-or-more person families                                          216 non-null    object
 36  FAMILY INCOME BY NUMBER OF EARNERS                                     0 non-null      object
 37      No earners                                                         216 non-null    object
 38      1 earner                                                           216 non-null    object
 39      2 earners                                                          216 non-null    object
 40      3 or more earners                                                  216 non-null    object
 41  NONFAMILY HOUSEHOLDS                                                   0 non-null      object
 42      Nonfamily households                                               216 non-null    object
 43          Female householder                                             216 non-null    object
 44              Living alone                                               216 non-null    object
 45              Not living alone                                           216 non-null    object
 46          Male householder                                               216 non-null    object
 47              Living alone                                               216 non-null    object
 48              Not living alone                                           216 non-null    object
dtypes: object(49)
memory usage: 82.8+ KB